### ISSUE TITLE
Monster Variants 

### ISSUE THREAD

**Issue by acedward** [PaimaStudios/tarochi-game#126] opened 2024-04-03 13:28 UTC
<img width="611" alt="Screenshot 2024-04-03 at 10 27 40" src="https://github.com/PaimaStudios/tarochi-game/assets/3951895/b051ad14-cd0d-4f9e-a446-d98ba60e6189">

* Define Rules & Mechanisms
* Define UI
* Implement Frontend
* Implement Backend
* How to apply retroactively?

**Comment by SebastienGllmt** [comment] 2024-05-28 20:22
Duplicate of #156

**Closed as completed by SebastienGllmt** 2024-05-28 20:22 UTC
Labels: enhancement
