### ISSUE TITLE
Lovers achievement does not clear

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#140] opened 2024-04-25 19:46 UTC
I've seen this mentioned as an issue multiple times in Discord
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/3d90e7d0-20c9-4517-82f4-de7287bd0899)

**Comment by acedward** [comment] 2024-04-25 21:38
It looks like the interaction system broke at some point.

Talking to NPCs use any of the nearest 8 blocks and talk "randomly" to one of them, instead of the nearest or where the player is "looking"

**Comment by SebastienGllmt** [comment] 2024-05-27 13:20
I think this was fixed by putting the NPCs slightly further apart, right? Presumably the underlying issue is the same as #150 though

**Comment by RadinEth** [comment] 2024-06-02 18:11
I can confirm this is fixed now.

**Closed as completed** 2024-06-02 18:16 UTC
Labels: bug
